# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AtlasGrid
                                 A QGIS plugin
 This plugin can be used for creating a regular coverage grid for atlas plots
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Styrke10 ApS
        email                : morten@styrke10.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import Qgis, QgsProject, QgsVectorLayer, QgsFeature, QgsFeatureRequest, QgsExpression, QgsField, QgsRectangle, QgsGeometry, QgsMessageLog
from qgis import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .atlasgrid_dialog import AtlasGridDialog
import os.path


class AtlasGrid:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AtlasGrid_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AtlasGrid')
        

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AtlasGrid', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/atlasgrid/atlasgrid.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AtlasGrid'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AtlasGrid'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AtlasGridDialog()
            # Set default CRS and extent
            mapCanvas = self.iface.mapCanvas()
            self.dlg.mExtentGroupBox.setOriginalExtent(mapCanvas.extent(),mapCanvas.mapSettings().destinationCrs())
            self.dlg.cmbCrsSelection.setCrs(mapCanvas.mapSettings().destinationCrs())

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            layout = self.dlg.cmb_PrintLayouts.currentText()
            map = self.dlg.cmb_MapItems.currentText()
            extent = self.dlg.mExtentGroupBox.outputExtent()
            self.rwDimension = None
            self.nRowsAndCols = None

            
            for item in self.dlg.maplist:
                if item[0] == layout and item[1] == map:
                    mapScale = item[2]
                    mapsheetExtent = item[3]
            
            self.createGrid()
            
            
    def createGrid(self):
        # create layer
        gridLayer = QgsVectorLayer("Polygon?crs={}".format(self.dlg.cmbCrsSelection.crs().authid()), 'AtlasGrid', "memory")

        QgsProject.instance().addMapLayer(gridLayer)

        fieldName = 'cellname'
        field = QgsField(fieldName, QVariant.String)
        numfield = QgsField('cellnum', QVariant.Int)
        gridLayer.dataProvider().addAttributes([field,numfield])
        gridLayer.updateFields()

        # get extent of the grid
        extent = self.dlg.gridExtent
        rwDim = self.dlg.rwDimensions

        # calculate start rectangle as upper leftmost rectangle
        x = extent.xMinimum()
        y = extent.yMaximum() - rwDim[1]
        prefix = ''
        colname = 'A'
        rownum = 1

        gridLayer.startEditing()

        # generate the net
        for i in range(0,self.dlg.nRowsAndCols[0]):
            for j in range(0,self.dlg.nRowsAndCols[1]):
                rectangle = QgsRectangle(x, y, x + rwDim[0], y + rwDim[1])
                cellname = "{}{}{}".format(prefix,colname,str(rownum))
                feat = QgsFeature(gridLayer.fields())
                feat.setAttribute(fieldName, cellname)
                feat.setGeometry(QgsGeometry.fromRect(rectangle))
                gridLayer.dataProvider().addFeatures([feat])

                x += rwDim[2]
                if colname < 'Z':
                    colname = chr(ord(colname)+1)
                else:
                    if prefix == '':
                        prefix = 'A'
                    else:
                        prefix = chr(ord(prefix)+1)
                    colname = 'A'

            x = extent.xMinimum()
            y -= rwDim[3]
            rownum += 1
            colname = 'A'
            prefix = ''

        # Check for non-intersecting cells if user has chosen to do so
        if self.dlg.chkboxDeleteNonIntersecting.isChecked():
            toBeDeleted = self.deleteNonIntersecting(gridLayer)
        else:
            toBeDeleted = []
        
        # Delete cells not intersecting and number the remaining
        n = 0
        for f in gridLayer.getFeatures():
            if f["cellname"] in toBeDeleted:
                gridLayer.deleteFeature(f.id())
            else:
                n += 1
                f["cellnum"] = n
                gridLayer.updateFeature(f)

        gridLayer.commitChanges()


    def deleteNonIntersecting(self,grid):
        # Generate line layer from grid polygons
        lines = processing.run("native:polygonstolines", {'INPUT':grid,'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
        
        # Split polygons by lines
        split = processing.run('native:splitwithlines', {'INPUT':grid,'LINES':lines, 'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']

        # Add the split layer temporarily to the project (to be able to reference it in a field calculator expression)
        QgsProject.instance().addMapLayer(split, addToLegend=False)
        split.setName('split')
        splitToDelete = split

        # Use field calculator to determine which cells overlap each other
        alg_params = {
            'FIELD_LENGTH': 20,
            'FIELD_NAME': 'overlaps',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 2,  # Text
            'FORMULA': "array_to_string(array_sort( aggregate( layer:= '{}', aggregate:='array_agg', expression:=cellname, filter:=contains($geometry, geometry(@parent)))))".format(split.name()),
            'INPUT': split,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }
        split = processing.run('native:fieldcalculator', alg_params)['OUTPUT']

        # Use field calculator to determine which cells to keep initially
        aoiLayer = self.dlg.cmbAOILayer.currentLayer()
        alg_params = {
            'FIELD_LENGTH': 0,
            'FIELD_NAME': 'keep',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 6,  # Boolean
            'FORMULA': "aggregate( layer:= '{}', aggregate:='count', expression:=@id, filter:=intersects($geometry, geometry(@parent))) > 0".format(aoiLayer.name()),
            'INPUT': split,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }
        split = processing.run('native:fieldcalculator', alg_params)['OUTPUT']

        # Check for intersection in the overlaps
        split.startEditing()
        for f in split.getFeatures():
            overlaps = f["overlaps"].split(',') if f["overlaps"] else []
            if f["keep"] and len(overlaps)>1:
                str = "cellname in ({}) and cellname = overlaps".format(','.join("'{}'".format(o) for o in overlaps))
                request = QgsFeatureRequest(QgsExpression(str))
                alreadyKept = False
                for o in split.getFeatures(request):
                    if o["keep"]:
                        alreadyKept = True
                
                if not alreadyKept:
                    o["keep"] = True
                    split.updateFeature(o)
                    
        split.commitChanges()

        str = "cellname = overlaps and not keep"
        request = QgsFeatureRequest(QgsExpression(str))
        toBeDeleted = []
        for f in split.getFeatures(request):
            toBeDeleted.append(f["cellname"])
            
        # Remove the temporary layer again
        QgsProject.instance().removeMapLayer(splitToDelete)
        
        return toBeDeleted

