# -*- coding: utf-8 -*-

"""
/***************************************************************************
 EjdEjerInfo
                                 A QGIS plugin
 Hent info om ejer(e) af danske ejendomme fra Ejerfortegnelsen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-17
        copyright            : (C) 2024 by Morten Storm, Styrke 10 ApS
        email                : morten@styrke10.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Morten Storm, Styrke 10 ApS'
__date__ = '2025-06-05'
__copyright__ = '(C) 2025 by Morten Storm, Styrke 10 ApS'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from qgis.utils import iface
from .atlasgrid_provider import AtlasGridProvider
from .config import Settings, OptionsFactory

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class AtlasGridProcessing(object):

    def __init__(self):
        self.provider = None

        # Initiate config 
        self.settings = Settings()
        self.options_factory = OptionsFactory(self.settings)
        self.options_factory.setTitle('AtlasGrid')
        iface.registerOptionsWidgetFactory(self.options_factory)

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = AtlasGridProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
